<?xml version="1.0"?>
<package format="3">
  <name>hpp-core</name>
  <version>8.0.0</version>
  <description>Implement basic classes for canonical path planning for kinematic chains. </description>

  <maintainer email="guilhem.saurel@laas.fr">Guilhem Saurel</maintainer>

  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux et al.</author>

  <license>BSD-2</license>

  <url type="website">https://github.com/humanoid-path-planner/hpp-core</url>
  <url type="repository">https://github.com/humanoid-path-planner/hpp-core</url>
  <url type="bugtracker">https://github.com/humanoid-path-planner/hpp-core/issues</url>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>
  <buildtool_depend>cmake</buildtool_depend>

  <build_depend>doxygen</build_depend>

  <depend>coal</depend>
  <depend>boost</depend>
  <depend>eigen</depend>
  <depend>hpp-constraints</depend>
  <depend>hpp-pinocchio</depend>
  <depend>hpp-statistics</depend>
  <depend>hpp-util</depend>
  <depend>proxsuite</depend>

  <test_depend>example-robot-data</test_depend>
  <test_depend>hpp-environments</test_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
