[build-system]
build-backend = "cmeel"
requires = [
  "cmeel-boost[build] ~= 1.90.0",
  "cmeel[build]",
  "hpp-constraints[build]",
  "hpp-pinocchio[build]",
  "hpp-statistics[build]",
  "hpp-util[build]",
  "proxsuite[build]"
]

[project]
dependencies = [
  "cmeel-boost ~= 1.90.0",
  "hpp-constraints",
  "hpp-pinocchio",
  "hpp-statistics",
  "hpp-util",
  "proxsuite"
]
description = "Utility classes for testing (robust) equilibrium of a system in contact with the environment, and other centroidal dynamics methods"
license = "BSD-2-Clause"
name = "hpp-core"
version = "9.0.2"

[tool.cmeel]
has-sitelib = false

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
